-- UZH Studiengänge 2025 (alphabetisch) + Legacy-Aliase
DELETE FROM public.study_programs;
DELETE FROM public.r4_department_scopes WHERE all_departments = false;
DELETE FROM public.departments;
INSERT INTO public.departments (slug, name, sort_order) VALUES ('mnf', 'Mathematisch-naturwissenschaftliche Fakultät', 10);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('mef', 'Medizinische Fakultät', 20);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('phf', 'Philosophische Fakultät', 30);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('rwf', 'Rechtswissenschaftliche Fakultät', 40);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('trf', 'Theologische und Religionswissenschaftliche Fakultät', 50);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('wwf', 'Wirtschaftswissenschaftliche Fakultät', 60);
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Biochemie', 'bachelor', 1 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Biologie', 'bachelor', 2 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Biomedizin', 'bachelor', 3 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Chemie', 'bachelor', 4 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Wirtschaftschemie', 'bachelor', 5 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Erdsystemwissenschaften', 'bachelor', 6 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Geographie', 'bachelor', 7 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Mathematik', 'bachelor', 8 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Physik', 'bachelor', 9 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Biochemistry', 'master', 10 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Biology', 'master', 11 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Biomedicine', 'master', 12 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Chemical and Molecular Sciences', 'master', 13 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Wirtschaftschemie', 'master', 14 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Earth System Sciences', 'master', 15 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Geography', 'master', 16 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Mathematics', 'master', 17 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Physics', 'master', 18 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Computational Science', 'master', 19 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Data Science', 'master', 20 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Interdisciplinary Brain Sciences', 'master', 21 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Neural Systems and Computation', 'master', 22 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Quantitative Environmental Sciences', 'master', 23 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Theoretical Astrophysics and Cosmology', 'master', 24 FROM public.departments WHERE slug = 'mnf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'B Med Humanmedizin', 'bachelor', 25 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'B Med Dent Zahnmedizin', 'bachelor', 26 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'B Med Chiro Chiropraktische Medizin', 'bachelor', 27 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'M Med Humanmedizin', 'master', 28 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'M Med Dent Zahnmedizin', 'master', 29 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'M Med Chiro Chiropraktische Medizin', 'master', 30 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Biomedical Sciences', 'master', 31 FROM public.departments WHERE slug = 'mef' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Psychologie', 'bachelor', 32 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Publizistik- und Kommunikationswissenschaft', 'bachelor', 33 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Erziehungswissenschaft', 'bachelor', 34 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Politikwissenschaft', 'bachelor', 35 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Soziologie', 'bachelor', 36 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Ethnologie', 'bachelor', 37 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Gender Studies', 'bachelor', 38 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Geschichte', 'bachelor', 39 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Philosophie', 'bachelor', 40 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Filmwissenschaft', 'bachelor', 41 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Kunstgeschichte', 'bachelor', 42 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Musikwissenschaft', 'bachelor', 43 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Populäre Kulturen', 'bachelor', 44 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Computerlinguistik und Sprachtechnologie', 'bachelor', 45 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Digital Humanities', 'bachelor', 46 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Deutsche Sprach- und Literaturwissenschaft', 'bachelor', 47 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA English Literature and Linguistics', 'bachelor', 48 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Romanische Sprachen und Literaturen', 'bachelor', 49 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Slavische Sprach- und Literaturwissenschaft', 'bachelor', 50 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Allgemeine und Vergleichende Literaturwissenschaft', 'bachelor', 51 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Vergleichende Sprachwissenschaft', 'bachelor', 52 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Nah- und Mitteloststudien', 'bachelor', 53 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Ostasienwissenschaften', 'bachelor', 54 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Archäologien', 'bachelor', 55 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Altertumswissenschaften', 'bachelor', 56 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Psychologie', 'master', 57 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Publizistik- und Kommunikationswissenschaft', 'master', 58 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Erziehungswissenschaft', 'master', 59 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Politikwissenschaft', 'master', 60 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Soziologie', 'master', 61 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Ethnologie', 'master', 62 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Gender Studies', 'master', 63 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Geschichte', 'master', 64 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Philosophie', 'master', 65 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Filmwissenschaft', 'master', 66 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Kunstgeschichte', 'master', 67 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Musikwissenschaft', 'master', 68 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Populäre Kulturen', 'master', 69 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Computational Linguistics and Language Technology', 'master', 70 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Digital Humanities', 'master', 71 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Deutsche Sprach- und Literaturwissenschaft', 'master', 72 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA English Literature and Linguistics', 'master', 73 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Romanische Sprach- und Literaturwissenschaft', 'master', 74 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Slavische Sprach- und Literaturwissenschaft', 'master', 75 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Allgemeine und Vergleichende Literaturwissenschaft', 'master', 76 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Vergleichende Sprachwissenschaft', 'master', 77 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA East Asian Studies', 'master', 78 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Interdisziplinäre Kulturstudien', 'master', 79 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Archäologie und Altertumswissenschaften', 'master', 80 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BLaw Rechtswissenschaft', 'bachelor', 81 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MLaw Rechtswissenschaft', 'master', 82 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MLaw International and Comparative Law', 'master', 83 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'B Th Theologie', 'bachelor', 84 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Religionswissenschaft', 'bachelor', 85 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'M Th Theologie', 'master', 86 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Religionswissenschaft', 'master', 87 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Religion – Wirtschaft – Politik', 'master', 88 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Antike Religionen (Religions in the Ancient World)', 'master', 89 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Religionsphilosophie / Religion and Science', 'master', 90 FROM public.departments WHERE slug = 'trf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Wirtschaftswissenschaften', 'bachelor', 91 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Informatik', 'bachelor', 92 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Wirtschaftsinformatik', 'bachelor', 93 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Business Administration', 'master', 94 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Economics', 'master', 95 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Banking and Finance', 'master', 96 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Management and Economics', 'master', 97 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Informatik', 'master', 98 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Wirtschaftsinformatik', 'master', 99 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Quantitative Finance', 'master', 100 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Computer Science', 'bachelor', 101 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Information & Cyber Security', 'bachelor', 102 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Immersive Technologies', 'bachelor', 103 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Computer Science', 'master', 104 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Information & Cyber Security', 'master', 105 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Immersive Technologies', 'master', 106 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Economics and Data Science', 'bachelor', 107 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Business Administration', 'bachelor', 108 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Economics and Data Science', 'master', 109 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Business Administration', 'master', 110 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Digital Ideation', 'bachelor', 111 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Digital Ideation', 'master', 112 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Rechtswissenschaft', 'bachelor', 113 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Rechtswissenschaften', 'bachelor', 114 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Rechtswissenschaften', 'master', 115 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Economics', 'master', 116 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BLaw Rechtswissenschaft'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'Rechtswissenschaft';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Computer Science';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Information & Cyber Security';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Immersive Technologies';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Computer Science';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Information & Cyber Security';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MSc Informatik'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Immersive Technologies';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BA Wirtschaftswissenschaften'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Business Administration';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BA Wirtschaftswissenschaften'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Economics and Data Science';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MA Business Administration'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Business Administration';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MA Economics'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Economics and Data Science';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MA Economics'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'Economics';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BA Digital Humanities'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BA Digital Ideation';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MA Digital Humanities'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MA Digital Ideation';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('BLaw Rechtswissenschaft'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'BSc Rechtswissenschaften';
UPDATE public.applications SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{personalData,studiengang}', to_jsonb('MLaw Rechtswissenschaft'::text), true) WHERE TRIM(data->'personalData'->>'studiengang') = 'MSc Rechtswissenschaften';
INSERT INTO public.r4_department_scopes (user_id, all_departments, department_id)
SELECT u.id, true, NULL FROM public.users u WHERE u.email = 'r4.test@example.com'
ON CONFLICT (user_id) DO UPDATE SET all_departments = EXCLUDED.all_departments, department_id = EXCLUDED.department_id;
INSERT INTO public.r4_department_scopes (user_id, all_departments, department_id)
SELECT u.id, false, d.id FROM public.users u CROSS JOIN public.departments d
WHERE u.email = 'r4.rf.test@example.com' AND d.slug = 'rwf'
ON CONFLICT (user_id) DO UPDATE SET all_departments = EXCLUDED.all_departments, department_id = EXCLUDED.department_id;
