-- UZH faculties + study programs (Prototyp)
DELETE FROM public.study_programs;
DELETE FROM public.r4_department_scopes WHERE all_departments = false;
DELETE FROM public.departments;
INSERT INTO public.departments (slug, name, sort_order) VALUES ('trf', 'Theologische und Religionswissenschaftliche Fakultät', 10);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('rwf', 'Rechtswissenschaftliche Fakultät', 20);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('wwf', 'Wirtschaftswissenschaftliche Fakultät', 30);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('mef', 'Medizinische Fakultät', 40);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('vsf', 'Vetsuisse-Fakultät', 50);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('mnf', 'Mathematisch-naturwissenschaftliche Fakultät', 60);
INSERT INTO public.departments (slug, name, sort_order) VALUES ('phf', 'Philosophische Fakultät', 70);
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Theologie', 'bachelor', 1 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Religionswissenschaft', 'bachelor', 2 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Theologie', 'master', 3 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Religionswissenschaft', 'master', 4 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Religion – Wirtschaft – Politik', 'master', 5 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Antike Religionen (Religions in the Ancient World)', 'master', 6 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Religionsphilosophie / Religion and Science', 'master', 7 FROM public.departments WHERE slug = 'trf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Rechtswissenschaft', 'bachelor', 8 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Rechtswissenschaft (General Studies)', 'master', 9 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Rechtswissenschaft: Rechtsschöpfung und Rechtsanwendung', 'master', 10 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Rechtswissenschaft: Wirtschaftsrecht', 'master', 11 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'International and Comparative Law (English program)', 'master', 12 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Double Degree Programme (UZH / Kooperationsuniversitäten)', 'master', 13 FROM public.departments WHERE slug = 'rwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftswissenschaften (Schwerpunkt Betriebswirtschaftslehre)', 'bachelor', 14 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftswissenschaften (Schwerpunkt Volkswirtschaftslehre)', 'bachelor', 15 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftswissenschaften (Schwerpunkt Banking and Finance)', 'bachelor', 16 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftswissenschaften (Schwerpunkt Management and Economics)', 'bachelor', 17 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Informatik (Schwerpunkte: Software Systems, People and Computing, Artificial Intelligence)', 'bachelor', 18 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftsinformatik', 'bachelor', 19 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Business Administration', 'master', 20 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Economics', 'master', 21 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Banking and Finance', 'master', 22 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Management and Economics', 'master', 23 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Quantitative Finance', 'master', 24 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Informatik (Spezialisierungen: Data Science, Artificial Intelligence, Software Systems)', 'master', 25 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftsinformatik', 'master', 26 FROM public.departments WHERE slug = 'wwf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Humanmedizin', 'bachelor', 27 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Zahnmedizin', 'bachelor', 28 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Chiropraktische Medizin', 'bachelor', 29 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Humanmedizin', 'master', 30 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Zahnmedizin', 'master', 31 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Chiropraktische Medizin', 'master', 32 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biomedical Sciences (Specialized Master)', 'master', 33 FROM public.departments WHERE slug = 'mef';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Veterinärmedizin', 'bachelor', 34 FROM public.departments WHERE slug = 'vsf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Veterinärmedizin', 'master', 35 FROM public.departments WHERE slug = 'vsf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biochemie', 'bachelor', 36 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biologie', 'bachelor', 37 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biomedizin', 'bachelor', 38 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Chemie', 'bachelor', 39 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftschemie', 'bachelor', 40 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Erdsystemwissenschaften', 'bachelor', 41 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Geographie', 'bachelor', 42 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Mathematik', 'bachelor', 43 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Physik', 'bachelor', 44 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biochemistry', 'master', 45 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biology', 'master', 46 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Biomedicine', 'master', 47 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Chemical and Molecular Sciences', 'master', 48 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Wirtschaftschemie', 'master', 49 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Earth System Sciences', 'master', 50 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Geography', 'master', 51 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Mathematics', 'master', 52 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Physics', 'master', 53 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Computational Science (Specialized Master)', 'master', 54 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Data Science (Specialized Master)', 'master', 55 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Interdisciplinary Brain Sciences (Specialized Master)', 'master', 56 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Neural Systems and Computation (Specialized Master)', 'master', 57 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Quantitative Environmental Sciences (Specialized Master)', 'master', 58 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Theoretical Astrophysics and Cosmology (Specialized Master)', 'master', 59 FROM public.departments WHERE slug = 'mnf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Psychologie', 'bachelor', 60 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Publizistik- und Kommunikationswissenschaft', 'bachelor', 61 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Erziehungswissenschaft', 'bachelor', 62 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Politikwissenschaft', 'bachelor', 63 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Soziologie', 'bachelor', 64 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Ethnologie (Social Anthropology)', 'bachelor', 65 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Gender Studies', 'bachelor', 66 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Geschichte', 'bachelor', 67 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Philosophie', 'bachelor', 68 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Filmwissenschaft', 'bachelor', 69 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Kunstgeschichte', 'bachelor', 70 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Musikwissenschaft', 'bachelor', 71 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Populäre Kulturen', 'bachelor', 72 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Computerlinguistik und Sprachtechnologie', 'bachelor', 73 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Digital Humanities', 'bachelor', 74 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Deutsche Sprach- und Literaturwissenschaft', 'bachelor', 75 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'English Literature and Linguistics', 'bachelor', 76 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Romanische Sprachen und Literaturen (Französisch, Italienisch, Iberoromanisch)', 'bachelor', 77 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Slavische Sprach- und Literaturwissenschaft', 'bachelor', 78 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Allgemeine und Vergleichende Literaturwissenschaft', 'bachelor', 79 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Vergleichende Sprachwissenschaft', 'bachelor', 80 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Nah- und Mitteloststudien / Islamwissenschaft', 'bachelor', 81 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Ostasienwissenschaften (Japanologie, Sinologie)', 'bachelor', 82 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Archäologien (Klassische, Prähistorische, Provinzialrömische)', 'bachelor', 83 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Altertumswissenschaften', 'bachelor', 84 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Psychologie', 'master', 85 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Publizistik- und Kommunikationswissenschaft', 'master', 86 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Erziehungswissenschaft', 'master', 87 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Politikwissenschaft', 'master', 88 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Soziologie', 'master', 89 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Ethnologie / Social Anthropology', 'master', 90 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Gender Studies', 'master', 91 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Geschichte', 'master', 92 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Philosophie', 'master', 93 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Filmwissenschaft', 'master', 94 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Kunstgeschichte (Art History)', 'master', 95 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Musikwissenschaft', 'master', 96 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Populäre Kulturen', 'master', 97 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Computational Linguistics and Language Technology', 'master', 98 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Digital Humanities', 'master', 99 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Deutsche Sprach- und Literaturwissenschaft', 'master', 100 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'English Literature and Linguistics', 'master', 101 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Romanische Sprach- und Literaturwissenschaft', 'master', 102 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Slavische Sprach- und Literaturwissenschaft', 'master', 103 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Allgemeine und Vergleichende Literaturwissenschaft', 'master', 104 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Vergleichende Sprachwissenschaft', 'master', 105 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'East Asian Studies', 'master', 106 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Interdisziplinäre Kulturstudien', 'master', 107 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'Archäologie und Altertumswissenschaften', 'master', 108 FROM public.departments WHERE slug = 'phf';
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Computer Science', 'bachelor', 109 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Information & Cyber Security', 'bachelor', 110 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Immersive Technologies', 'bachelor', 111 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Computer Science', 'master', 112 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Information & Cyber Security', 'master', 113 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Immersive Technologies', 'master', 114 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Economics and Data Science', 'bachelor', 115 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Business Administration', 'bachelor', 116 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Economics and Data Science', 'master', 117 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Business Administration', 'master', 118 FROM public.departments WHERE slug = 'wwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BA Digital Ideation', 'bachelor', 119 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MA Digital Ideation', 'master', 120 FROM public.departments WHERE slug = 'phf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'BSc Rechtswissenschaften', 'bachelor', 121 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;
INSERT INTO public.study_programs (department_id, name, degree_level, sort_order) SELECT id, 'MSc Rechtswissenschaften', 'master', 122 FROM public.departments WHERE slug = 'rwf' ON CONFLICT (name) DO NOTHING;

INSERT INTO public.r4_department_scopes (user_id, all_departments, department_id)
SELECT u.id, true, NULL FROM public.users u WHERE u.email = 'r4.test@example.com'
ON CONFLICT (user_id) DO UPDATE SET all_departments = EXCLUDED.all_departments, department_id = EXCLUDED.department_id;
INSERT INTO public.r4_department_scopes (user_id, all_departments, department_id)
SELECT u.id, false, d.id FROM public.users u CROSS JOIN public.departments d
WHERE u.email = 'r4.rf.test@example.com' AND d.slug = 'rwf'
ON CONFLICT (user_id) DO UPDATE SET all_departments = EXCLUDED.all_departments, department_id = EXCLUDED.department_id;
